version: '3.8'

services:
  game-platform:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # These should be set via .env file or environment variables
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Convex Configuration
      - CONVEX_DEPLOYMENT=${CONVEX_DEPLOYMENT}
      - NEXT_PUBLIC_CONVEX_URL=${NEXT_PUBLIC_CONVEX_URL}
      # Email Configuration
      - RESEND_API_KEY=${RESEND_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      # App Configuration
      - NEXT_PUBLIC_APP_DOMAIN=${NEXT_PUBLIC_APP_DOMAIN}
      - SITE_URL=${SITE_URL}
      # JWT Configuration
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY}
      - JWKS=${JWKS}
      # Setup flag
      - SETUP_SCRIPT_RAN=${SETUP_SCRIPT_RAN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3