// AI MCQ Quiz game type - Question generation is done via action

export interface MCQQuestion {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
}

export interface AIQuizConfig {
  topic: string;
  difficultyLevel: number; // 1-20
  questionCount: number;
}

/**
 * For AI MCQ games, questions are pre-generated via an action before game creation
 * The action calls OpenRouter, generates questions, and passes them via customConfig
 * This function simply extracts and returns them
 */
export function generateQuestions(customConfig?: any): MCQQuestion[] {
  // If questions were pre-generated by the action, return them
  if (customConfig?.questions && Array.isArray(customConfig.questions)) {
    return customConfig.questions;
  }

  // Fallback: return a placeholder (shouldn't normally happen)
  return [
    {
      id: 1,
      question: "Loading questions...",
      options: ["Please wait", "Questions loading", "Starting soon", "Hold on"],
      correctAnswer: 0,
    },
  ];
}
